### ISSUE TITLE
work with parallel

### ISSUE THREAD

**Issue by Freed-Wu** [lljbash/tmux-update-display#2]
```shell
$ $parallel --tmux vi ::: {1..3}
See output with: tmux -S /tmp/tms1NdzV attach
$ tmux -S /tmp/tms1NdzV attach
```

will
![Screenshot from 2021-08-19 04-23-35](https://user-images.githubusercontent.com/32936898/129967343-2fcea6a8-7477-4325-b105-fbf43601b26d.png)

the `export DISPLAY=1` be inputted to vi.

How can avoid this situation?

**Comment by lljbash** [comment]
看了 parallel 源码, 它的 command 会 wrap 一层 login_shell, 所以 `parallel --tmux` 下 `#{pane_current_command}` 是 login_shell. 检测不到 vi.

Workaround: 可以在检查 `pane_process` 的部分自己检查一下 `${pane_process[0]}` 是不是 p 开头的, 跳过 parallel 建立的 tmux session.

**Comment by Freed-Wu** [comment]
```diff
--- a/scripts/tmux-update-display.sh
+++ b/scripts/tmux-update-display.sh
@@ -28,6 +28,10 @@ tmux list-panes -s -F "#{session_name}:#{window_index}.#{pane_index} #{pane_curr
 while read pane_process
 do
     IFS=' ' read -ra pane_process <<< "$pane_process"
+    # https://github.com/lljbash/tmux-update-display/issues/2
+    if [[ "${pane_process[0]}" == p* ]]; then
+        break
+    fi
     if [[ "${pane_process[1]}" == "bash" ]]; then
         tmux send-keys -t ${pane_process[0]} ^E ^U "export DISPLAY=$NEW_DISPLAY" Enter ^Y ^E
     elif [[ "${pane_process[1]}" == "zsh" ]]; then
```

It looks can solve this problem. (Although this solution looks weird.)

**Comment by Freed-Wu** [comment]
Excuse me:confused: Any progress about this issue:question:

**Comment by lljbash** [comment]
> Excuse me😕 Any progress about this issue❓

You can just use your own fork.
