### ISSUE TITLE
[advice] use exists to judge neovim and vim

### ISSUE THREAD

**Issue by Freed-Wu** [lljbash/tmux-update-display#4]
<https://github.com/lljbash/tmux-update-display/blob/master/scripts/tmux-update-display.sh#L42>

Change `:xrestore` to `:execute exists(':xrestore') ? 'xrestore' : ''` can make this tmux plugin work on both neovim and vim.

Thanks!

**Comment by lljbash** [comment]
ok

**Comment by Freed-Wu** [comment]
<https://github.com/lljbash/tmux-update-display/blob/master/README.md?plain=1#L19> and <https://github.com/lljbash/tmux-update-display/blob/master/scripts/tmux-update-display.sh#L14> perhaps should be removed, too.
